tsqllint/tsqllint

- TSQLLINT_LIB/Rules/MultiTableAliasRule.cs
- TSQLLINT_TESTS/UnitTests/Rules/multi-table-alias/multi-table-alias-no-error.sql
Scripts containing common table expressions were being
flagged as violating the Multi Table Alias rule.
* Add new CTE Rulevisitor to capture CTE Names
* Pass List of CTE Names to Table Alias Visitor
Resolves #9
> Fix bug with MultiTableAliasRule and CTE

- TSQLLINT_LIB/Parser/SqlRuleVisitor.cs
- TSQLLINT_LIB/Rules/RuleViolations/RuleViolation.cs
- TSQLLINT_TESTS/IntegrationTests/integration-tests.cs
This fixes an issue where a SQL syntax error would show the type of error as "off".
> Fix syntax error to show "error" instead of "off"

- appveyor.yml
The AppVeyor file had a specific IP for NuGet, but AFAIK there is not necessary and looks like it was really a workaround for a long ago issue.
> Remove the NuGet IP from AppVeyor

- appveyor.yml
I read this was the recommended way to cache for NuGet and actually prevents any access to the NuGet hosts unless there was a dependency change.
> Cache the final NuGet package installed files

- scripts/install/install.js
Mr. Jaxon wasn't able to install this on his machine because the global Node.js directory is in Program Files. Fixing up the fixed APPDATA references to use the configured npm prefix will get it working better out of the box for folks :)
> Fix references to APPDATA

- TSQLLint.Lib/Plugins/PluginHandler.cs
If the path isn't a valid directory or file, the app is quiet.
> Report failure to find plugin

- README.md
- TSQLLint.Console/Application.cs
- TSQLLint.Console/ConfigHandler/CommandLineOptionHandler.cs
- TSQLLint.Console/ConfigHandler/CommandLineOptions.cs
- TSQLLint.Console/LintingHandler.cs
- TSQLLint.Lib/Config/ConfigReader.cs
- TSQLLint.Tests/IntegrationTests/ExistingConfigTests.cs
- TSQLLint.Tests/UnitTests/CommandLineOptions/CommandLineOptionHandlerTest.cs
- TSQLLint.Tests/UnitTests/Config/ConfigReaderTests.cs
- TSQLLint.Tests/UnitTests/PluginHandler/PluginHandlerTests.cs
Should now be able to use the -l option to list the plug-ins. As with print-config this will not do the linting.
Example message:
Found the following plugins:
Plugin Name 'mc-plugin' loaded from path 'D:/TFS/Repos/TSQLLint-MC-Plugin/bin/Debug/TSQLLint MC Plugin.dll'
> Ability to list plugins

- TSQLLint.Console/Application.cs
- TSQLLint.Lib/Plugins/Interfaces/IPluginHandler.cs
- TSQLLint.Lib/Plugins/PluginHandler.cs
- TSQLLint.Tests/UnitTests/PluginHandler/PluginHandlerTests.cs
Will log (not error) the fact that a Type was seen twice instead of loading it twice. Also fixed loading of plugins after config is parsed.
> Does not load a plugin in twice

- scripts/install.js
I was getting a malformed download url due to the process.arch value parsing in the script:
D:\Code\ChangeRequests\AppDB>npm install -g tsqllint
C:\Users\dgasperut\AppData\Roaming\npm\tsqllint -> C:\Users\dgasperut\AppData\Roaming\npm\node_modules\tsqllint\tsqllint.js
> tsqllint@1.8.6 install C:\Users\dgasperut\AppData\Roaming\npm\node_modules\tsqllint
> node ./scripts/install.js
Error: There was a problem downloading https://github.com/tsqllint/tsqllint/releases/download/v1.8.6/.tgz
at Writable.https.get.on (C:\Users\dgasperut\AppData\Roaming\npm\node_modules\tsqllint\scripts\install.js:37:27)
at emitOne (events.js:101:20)
at Writable.emit (events.js:188:7)
at Writable.RedirectableRequest._processResponse
> pr process.arch bug in setup script. 

- TSQLLint.Console/TSQLLint.Console.csproj
- TSQLLint.Lib/Parser/SqlRuleVisitor.cs
- TSQLLint.Lib/TSQLLint.Lib.csproj
- TSQLLint.Tests/FunctionalTests/ConsoleAppTests.cs
- TSQLLint.Tests/IntegrationTests/Configuration/CommandLineOptionTests.cs
- TSQLLint.Tests/IntegrationTests/IntegrationBaseTest.cs
- TSQLLint.Tests/UnitTests/Parser/SqlRuleVisitorTests.cs
This is so that the [extension can handle files with syntax errors](https://github.com/tsqllint/tsqllint-vscode-extension/issues/1).
> Allow files with syntax errors to be linted

- TSQLLint.Lib/Rules/SemicolonTerminationRule.cs
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/SemicolonTerminationRuleTests.cs
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/test-files/semicolon-termination-multiple-errors.sql
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/test-files/semicolon-termination-try-catch-while.sql
Throw semicolon error when missing; from end catch. This seems to be MSDN preference. 
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/try-catch-transact-sql
If there's a reason not to do this, I can make it an optional by putting it in it's own rule set.
> Issue 131 END CATCH;

- schema.json
Provides validation and autocomplete.
This should probably be published on http://schemastore.org/json/, so that editors pick it up automatically, but I thought I should add it here first.
> Add JSON schema for .tsqllintrc files

- README.md
- source/TSQLLint.Infrastructure/Interfaces/ISqlStreamReaderBuilder.cs
- source/TSQLLint.Infrastructure/Parser/SqlRuleVisitor.cs
- source/TSQLLint.Infrastructure/Parser/SqlStreamReaderBuilder.cs
- source/TSQLLint.Tests/UnitTests/Parser/SqlStreamReaderBuilderTests.cs
Many tools in the SQL ecosystem (e.g. [Invoke-Sqlcmd](https://docs.microsoft.com/en-us/powershell/module/sqlserver/invoke-sqlcmd)) support placeholders to inject variables into SQL scripts as shown in the example below:
```sql
SELECT * FROM foo WHERE bar = $(MyPlaceholder);
```
Currently TSQLLint throws a syntax error for files containing placeholders. This change adds support to TSQLLint for placeholder syntax by dereferencing any placeholders with values from environment variables before applying linting rules which enables use-cases like this:
```pwsh
Set-Content -Path query.sql -Value 'SELECT * FROM foo WHERE bar = $(MyPlaceholder);'
$env:MyPlaceholder = '123'
tsqllint query.sql
```
> Implement placeholder replacement

- README.md
- documentation/rules/conditional-begin-end.md
- documentation/rules/cross-database-transaction.md
- documentation/rules/data-compression.md
- documentation/rules/data-type-length.md
- documentation/rules/disallow-cursors.md
- documentation/rules/full-text.md
- documentation/rules/information-schema.md
- documentation/rules/keyword-capitalization.md
- documentation/rules/linked-server.md
- documentation/rules/multi-table-alias.md
- documentation/rules/named-constraint.md
- documentation/rules/non-sargable.md
- documentation/rules/object-property.md
- documentation/rules/print-statement.md
- documentation/rules/schema-qualify.md
- documentation/rules/select-star.md
- documentation/rules/semicolon-termination.md
- documentation/rules/set-ansi.md
- documentation/rules/set-nocount.md
- documentation/rules/set-quoted-identifier.md
- documentation/rules/set-transaction-isolation-level.md
- documentation/rules/set-variable.md
- documentation/rules/unicode-string.md
- documentation/rules/upper-lower.md
Closes #219 
Also adjusted existing docs for markdown formatting best practices & switched code blocks to `tsql` from `sql` for better syntax highlighting.
> Documentation

- README.md
- source/TSQLLint.Infrastructure/Configuration/ConfigFileGenerator.cs
- source/TSQLLint.Infrastructure/Configuration/ConfigReader.cs
- source/TSQLLint.Infrastructure/Configuration/Overrides/OverrideTypeMap.cs
- source/TSQLLint.Tests/UnitTests/ConfigFile/ConfigReaderTests.cs
- source/TSQLLint.Tests/UnitTests/ConfigFile/Overrides/OverrideTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRuleExceptions/RuleExceptionFinderOverrideFinderIntegrationTests.cs
- source/TSQLLint.Tests/UnitTests/Parser/InlineOverride_Tests.cs
- Added check for correctly spelled "compatibility-level" property with a fallback to the misspelled "compatability-level" property.
> Fixed misspelled "compatability-level" property

- README.md
- source/TSQLLint.Core/Interfaces/IConfigReader.cs
- source/TSQLLint.Core/TSQLLint.Core.csproj
- source/TSQLLint.Infrastructure/Configuration/ConfigReader.cs
- source/TSQLLint.Infrastructure/Parser/RuleVisitorBuilder.cs
- source/TSQLLint.Infrastructure/Plugins/PluginHandler.cs
- source/TSQLLint.Infrastructure/Rules/Common/BaseRuleVisitor.cs
- source/TSQLLint.Infrastructure/TSQLLint.Infrastructure.csproj
- source/TSQLLint.Tests/TSQLLint.Tests.csproj
- source/TSQLLint.Tests/UnitTests/LintingRuleVisitorBuilder/RuleVisitorBuilderIgnoreRulesTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRuleVisitorBuilder/RuleVisitorBuilderTest.cs
- source/TSQLLint.Tests/UnitTests/PluginHandler/TestPluginRule.cs
- source/TSQLLint/Application.cs
- source/TSQLLint/TSQLLint.csproj
- Make all rules that go to `RuleVisitorBuilder`.
- Updated to retrieve `RuleViolationSeverity` from `ISqlLintRule`.
- Updated code to not use `IPluginWithRules` and use new `IPlugin.GetRules` method.
- Updated `TSQLLint.Common` to version `3.3.0`.
- Updated some Nuget dependencies that were either minor or patch updates.
- Updated Readme file to include updated plugin example code.
> Plugins support default `RuleSeverity` value and use applications TSQLParser

- scripts/dotnet_build_test.sh
- scripts/dotnet_build_test_local.sh
- source/TSQLLint.sln
- Skip coverage results post to coveralls due to .net6 incompatibility.
- Updated solution items.
- Updated local build test script to use .net6.0 instead of .net5.0
> Mute coveralls error from posting coverage results due to .net6.0 incompatibility

- source/TSQLLint.Infrastructure/Parser/SqlRuleVisitor.cs
- source/TSQLLint.Tests/FunctionalTests/ConsoleAppTests.cs
- source/TSQLLint.Tests/FunctionalTests/TestFiles/with-dynamic-sql.sql
- source/TSQLLint.Tests/UnitTests/PluginHandler/TestPlugin.cs
- source/TSQLLint.Tests/UnitTests/PluginHandler/TestPluginRule.cs
- Fixed issue where if a file was parsed with dynamic sql having a plugin with rules loaded a casting exception would be thrown.
> fix-dynamic-sql-plugin-rules - Fix casting issue when parsing dynamic sql with a plugin with rules loaded.

- source/TSQLLint.Infrastructure/Reporters/ConsoleReporter.cs
- source/TSQLLint.Tests/UnitTests/Reporter/ReporterTests.cs
The Errors line item ends in a period, the Warnings probably should too.
Current output:
```
0 Errors.
0 Warnings
```
Expected:
```
0 Errors.
0 Warnings.
```
> Standardize period use in console output

- source/TSQLLint.Core/Interfaces/ICommandLineOptions.cs
- source/TSQLLint.Core/Interfaces/IGlobPatternMatcher.cs
- source/TSQLLint.Core/Interfaces/IIgnoreListReader.cs
- source/TSQLLint.Infrastructure/CommandLineOptions/CommandLineOptions.cs
- source/TSQLLint.Infrastructure/Configuration/IgnoreListReader.cs
- source/TSQLLint.Infrastructure/Parser/GlobPatternMatcher.cs
- source/TSQLLint.Infrastructure/Parser/SqlFileProcessor.cs
- source/TSQLLint.Infrastructure/TSQLLint.Infrastructure.csproj
- source/TSQLLint.Tests/FunctionalTests/.tsqllintignore
- source/TSQLLint.Tests/FunctionalTests/ConsoleAppTests.cs
- source/TSQLLint.Tests/FunctionalTests/TestFiles/IgnoreFolder1/ignored-file1.sql
- source/TSQLLint.Tests/FunctionalTests/TestFiles/IgnoreFolder1/ignored-file2.sql
- source/TSQLLint.Tests/FunctionalTests/TestFiles/IgnoreFolder2/IgnoreSubFolder/ignored-file3.sql
- source/TSQLLint.Tests/TSQLLint.Tests.csproj
- source/TSQLLint.Tests/UnitTests/ConfigFile/IgnoreListReaderTest.cs
- source/TSQLLint.Tests/UnitTests/Parser/SqlFileProcessorTests.cs
- source/TSQLLint/Application.cs
As #262  mentioned, is is useful to ignore some files in a folder. I added support for .tsqllintignore files, it will only be applied to those paths that point to a folder. I used [Microsoft.Extensions.FileSystemGlobbing](https://www.nuget.org/packages/Microsoft.Extensions.FileSystemGlobbing) to handle the glob pattern.
> Add support for ignore list file.

- source/TSQLLint.Tests/FunctionalTests/.tsqllintrc-plugins
- source/TSQLLint.Tests/FunctionalTests/ConsoleAppTests.cs
- source/TSQLLint.Tests/FunctionalTests/TestFiles/with-comment.sql
- source/TSQLLint.Tests/UnitTests/PluginHandler/TestPlugin.cs
- source/TSQLLint.Tests/UnitTests/PluginHandler/TestPluginRule.cs
- Added functional test for plugin rule loading and running.
- Also tests overridability of default plugin rule severity in `.tsqllintrc` files.
> add-get-rules-plugin-tests - Added functional test for plugin rule loading and running

- source/TSQLLint.Core/Interfaces/IAssemblyWrapper.cs
- source/TSQLLint.Infrastructure/Plugins/AssemblyWrapper.cs
- source/TSQLLint.Infrastructure/Plugins/PluginHandler.cs
- source/TSQLLint.Tests/UnitTests/PluginHandler/AssemblyWrapperTests.cs
- source/TSQLLint.Tests/UnitTests/PluginHandler/PluginHandlerTests.cs
Uses a more flexible load mechanism for getting plugins, allowing for plugins to have their own dependencies.
> Switch to LoadFrom rather than LoadFile to allow dependency loading

- .circleci/config.yml
- .editorconfig
- scripts/dotnet_build_test.sh
- source/.editorconfig
- source/TSQLLint.Core/TSQLLint.Core.csproj
- source/TSQLLint.Infrastructure/TSQLLint.Infrastructure.csproj
- source/TSQLLint.Tests/TSQLLint.Tests.csproj
- source/TSQLLint/TSQLLint.csproj
Add the possibility to run it with .NET 7
We want to upgrade in [MegaLinter](https://github.com/oxsecurity/megalinter) the SDK to .NET 7 but TSQLLint only works with .NET 6.
This PR adds the target to .NET 7 in addition to the existing one (.NET 6).
> Add .NET 7 support
