- TSQLLINT_CONSOLE/Application.cs
- TSQLLINT_CONSOLE/LintingHandler.cs
- TSQLLINT_CONSOLE/Reporters/ConsoleReporter.cs
- TSQLLINT_LIB/Parser/Interfaces/IReporter.cs
- TSQLLINT_LIB/Parser/RuleVisitorBuilder.cs
- TSQLLINT_LIB/Parser/SqlRuleVisitor.cs
- TSQLLINT_LIB/Rules/SchemaQualifyRule.cs
- TSQLLINT_TESTS/IntegrationTests/integration-tests.cs
- TSQLLINT_TESTS/UnitTests/RuleVisitorBuilder/RuleVisitorBuilderTest.cs
- TSQLLINT_TESTS/UnitTests/Rules/rule-tests.cs
- Move error reporting into rule visitor callback
- Replace list with IEneumerable
> Improve error reporting

- package.json
- scripts/install/install.js
- scripts/install/tsqllint
* Create install script
* Create postinstall hook
Resolves #16
> Fix Windows Git Bash Install

- appveyor.yml
- scripts/version-assembly.cmd
- scripts/version-package.cmd
- add NodeJs to build agent
- add npm pack
- add package to artifacts
> Build package in CI

- package.json
- scripts/install/install-dependencies.cmd
- scripts/install/install-dependencies.ps1
- scripts/install/install.js
- scripts/version-assembly.cmd
- scripts/version-package.cmd
> Install ScriptDom dependency when it doesnt exist on host machine

- README.md
> Add more instructions to installation

- TSQLLINT_LIB/Parser/SqlFileProcessor.cs
- TSQLLINT_TESTS/FunctionalTests/ConsoleAppTests.cs
- TSQLLINT_TESTS/IntegrationTests/IntegrationTests.cs
- TSQLLINT_TESTS/UnitTests/Parser/SqlFileProcessorTests.cs
> Fix directory doesnt exist bug

- README.md
- TSQLLINT_LIB/Config/ConfigFileGenerator.cs
- TSQLLINT_LIB/Parser/RuleVisitorBuilder.cs
- TSQLLINT_LIB/Rules/SetVariableRule.cs
- TSQLLINT_LIB/TSQLLINT_LIB.csproj
- TSQLLINT_TESTS/TSQLLINT_LIB_TESTS.csproj
- TSQLLINT_TESTS/UnitTests/Rules/rule-tests.cs
- TSQLLINT_TESTS/UnitTests/Rules/set-variable/set-variable-no-error.sql
- TSQLLINT_TESTS/UnitTests/Rules/set-variable/set-variable-one-error-mixed-state.sql
- TSQLLINT_TESTS/UnitTests/Rules/set-variable/set-variable-one-error.sql
- TSQLLINT_TESTS/UnitTests/Rules/set-variable/set-variable-two-errors.sql
- Create new "set variable rule" tests
- Create new rule
- Update config generator
- Update rule parser
> Add set variable rule

- TSQLLint.Lib/Parser/SqlFileProcessor.cs
- TSQLLint.Lib/Reporters/ConsoleReporter.cs
- TSQLLint.Tests/UnitTests/Parser/SqlRuleVisitorTest.cs
- TSQLLint.Tests/UnitTests/Reporter/ReporterTests.cs
- Improve ConsoleReporter testing converage
> Remove unused constructor in SqlFileProcessor

- TSQLLint.Lib/Rules/RuleViolations/RuleViolation.cs
- TSQLLint.Tests/UnitTests/CommadLineOptions/CommandLineOptionHandlingStrategies/CreateConfigFileStrategyTests.cs
- TSQLLint.Tests/UnitTests/Config/ConfigFileGeneratorTests.cs
- TSQLLint.Tests/UnitTests/Config/ConfigReaderTests.cs
- TSQLLint.Tests/UnitTests/Parser/SqlFileProcessorTests.cs
- TSQLLint.Tests/UnitTests/PluginHandler/PluginHandlerTests.cs
- TSQLLint.Tests/UnitTests/RuleVisitorBuilder/RuleVisitorBuilderTest.cs
- appveyor.yml
- Exclude OSX & Unix environment checks from code coverage
- Add code coverage report to artifacts
> Update Code Coverage Checks and Reporting

- appveyor.yml
- Add release hook
- Add encrypted github token
> Create release from Appveyor

- scripts/install.js
- scripts/version.sh
- Versions csproj, package.json, install.js script
> Add versioning script

- TSQLLint.Console/TSQLLint.Console.csproj
- TSQLLint.Lib/TSQLLint.Lib.csproj
- TSQLLint.Tests/TSQLLint.Tests.csproj
- scripts/cover.cmd
> Remove .net framework from build targets

- TSQLLint.Lib/Parser/RuleVisitorBuilder.cs
- TSQLLint.Lib/TSQLLint.Lib.csproj
- TSQLLint.Tests/TSQLLint.Tests.csproj
- TSQLLint.sln
- Update System.IO.Abstractions
- Reduce Complexity of BuildVisitors
> Update dependencies and reduce complexity

- TSQLLint.Lib/Rules/SemicolonTerminationRule.cs
- TSQLLint.Tests/TSQLLint.Tests.csproj
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/SemicolonTerminationRuleTests.cs
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/test-files/semicolon-termination-multiple-errors.sql
- TSQLLint.Tests/UnitTests/Rules/semicolon-termination/test-files/semicolon-termination-no-error-waitfor.sql
> Fix Semicolon Termination Waitfor Bug

- TSQLLint.Tests/TSQLLint.Tests.csproj
- TSQLLint.Tests/UnitTests/Parser/RuleExceptionFinder/RuleExceptionFinderTests.cs
- TSQLLint.Tests/UnitTests/Parser/RuleExceptionFinder/TestFiles/disable-rule-with-additional-comments.sql
- TSQLLint.Tests/UnitTests/Parser/RuleExceptionFinder/TestFiles/global-disable-rule-with-additional-comments.sql
- Create more tests for inline rule disablements that contain additional metadata
> Create more tests for inline rule disablements 

- TSQLLint.Lib/Parser/SqlRuleVisitor.cs
- TSQLLint.Tests/UnitTests/Parser/SqlRuleVisitorTests.cs
- Update rule visitor to honor global rule ignores when parsing invalid sql
> Update Parse Error Handling To Support Global Rule Ignores

- TSQLLint.Console/Application.cs
- TSQLLint.Lib/Config/ConfigFileGenerator.cs
- TSQLLint.Lib/Config/ConfigReader.cs
- TSQLLint.Tests/UnitTests/Config/ConfigReaderTests.cs
- Add compatability-level to generated tsqllintrc
- Rename compatability_level to compatability-level for consistency
> Rename compatability_level for consistency

- .release-it.json
- .travis.yml
- source/TSQLLint.Core/Constants.cs
- source/TSQLLint.Infrastructure/Parser/SqlFileProcessor.cs
- source/TSQLLint.Infrastructure/Rules/ConditionalBeginEndRule.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/ConditionalBeginEndRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/test-files/conditional-begin-end-multi-error.sql
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/test-files/conditional-begin-end-one-error-mixed-state.sql
- Remove npm publish prompt from release-it config
- Update to not lint files that contain non-terminated global ignores
- Update conditional-being-end rule to enforce on else statements ( Resolves #177 )
> Bug fixes & Tooling Updates

- source/TSQLLint.Console/appsettings.json
- source/TSQLLint.Infrastructure/Parser/SqlFileProcessor.cs
- source/TSQLLint.Infrastructure/TSQLLint.Infrastructure.csproj
parallel reading of files but serial processing because rest of code and sql scriptdom are not ready
was
https://github.com/tsqllint/tsqllint/pull/222
slightly worst but still great
Linted 1728 files in 4.5537925 seconds
> performance

- source/TSQLLint.sln
When loading the solution in Visual Studio 2019 and clicking on most of the files in the solution items folder, I get an error that the file isn't found (see screenshot below).
This pull request fixes the paths to the solution items to enable opening of all the files from within Visual Studio.
> Fix paths to solution items

- documentation/rules/delete-where.md
- documentation/rules/update-where.md
Add documentation for the new delete-where and update-where rules. Thanks for adding them!
> Add delete/update-where docs

- source/TSQLLint.Infrastructure/Rules/SemicolonTerminationRule.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/semicolon-termination/SemicolonTerminationRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/semicolon-termination/test-files/semicolon-termination-one-error-create-view.sql
Issue: https://github.com/tsqllint/tsqllint/issues/284
> Fix double semicolon-termination error in CREATE VIEW statement

- source/TSQLLint.Core/Interfaces/ISqlRule.cs
- source/TSQLLint.Infrastructure/Helpers/FixHelpers.cs
- source/TSQLLint.Infrastructure/Parser/ViolationFixer.cs
- source/TSQLLint.Infrastructure/Rules/Common/BaseRuleVisitor.cs
- source/TSQLLint.Infrastructure/Rules/Common/ColumnNumberCalculator.cs
- source/TSQLLint.Infrastructure/Rules/ConditionalBeginEndRule.cs
- source/TSQLLint.Infrastructure/Rules/KeywordCapitalizationRule.cs
- source/TSQLLint.Infrastructure/Rules/SemicolonTerminationRule.cs
- source/TSQLLint.Infrastructure/Rules/SetAnsiNullsRule.cs
- source/TSQLLint.Infrastructure/Rules/SetNoCountRule.cs
- source/TSQLLint.Infrastructure/Rules/SetQuotedIdentifierRule.cs
- source/TSQLLint.Infrastructure/Rules/SetTransactionIsolationLevelRule.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/RulesTestHelper.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/ConditionalBeginEndRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/test-files/conditional-begin-end-no-error.sql
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/test-files/conditional-else-begin-end-error.sql
- source/TSQLLint.Tests/UnitTests/LintingRules/conditional-begin-end/test-files/conditional-if-else-begin-end-error.sql
- source/TSQLLint.Tests/UnitTests/LintingRules/keyword-capitalization/KeywordCapitalizationRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/semicolon-termination/SemicolonTerminationRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/set-ansi/SetAnsiRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/set-nocount/SetNocountRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/set-quoted-identifier/SetQuotedIdentifierRuleTests.cs
- source/TSQLLint.Tests/UnitTests/LintingRules/set-transaction-isolation-level/SetTransactionIsolationLevelRuleTests.cs
* Add fix support for:
* /Rules/ConditionalBeginEndRule.cs
* /Rules/KeywordCapitalizationRule.cs
* /Rules/SemicolonTerminationRule.cs
* /Rules/SetAnsiNullsRule.cs
* /Rules/SetNoCountRule.cs
* /Rules/SetQuotedIdentifierRule.cs
* /Rules/SetTransactionIsolationLevelRule.cs
* Fixed a couple bugs with ConditionalBeginEndRule
* Demo:
> Add fix support for more rules

- README.md
> fix #297 typo in reademe

- .circleci/config.yml
- scripts/dotnet_package.sh
- scripts/github_create_release.sh
Try to fix https://github.com/tsqllint/tsqllint/issues/267
More context: https://github.com/tsqllint/tsqllint/issues/267#issuecomment-894998388
> Add more platforms
